name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustc --version
    - run: cargo build --all-targets --all-features

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add rustfmt
    - run: cargo fmt --version
    - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup toolchain install nightly-2023-01-23 --component clippy
    - run: cargo +nightly-2023-01-23 clippy --version
    - run: cargo +nightly-2023-01-23 clippy --features i64
    - run: cargo +nightly-2023-01-23 clippy --all-targets --features i64
    - run: cargo +nightly-2023-01-23 clippy --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustc --version
    - run: cargo test --features i64
    - run: cargo test --features i128
    - run: cargo test --no-default-features --lib --features i64
    - run: cargo test --no-default-features --lib --features i128
    - run: cargo test --no-default-features --lib --features std,i64
    - run: cargo test --no-default-features --lib --features serde,i64
    - run: cargo test --no-default-features --lib --features i64,borsh,parity
    - run: cargo test --no-default-features --lib --features i128,borsh,parity
    - run: cargo test --all-features

  run-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo run --example usage --features i64
